---
abstract: 'Be the most AVAR you can be'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101400, CPAN::Meta::Converter version 2.101390'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-AVAR
no_index:
  directory:
    - t
requires:
  Any::Moose: 0
  App::Nopaste: 0
  App::Nopaste::Service::Linode: 0
  App::QuoteCC: 0
  Bot::Training: 0
  Bot::Training::MegaHAL: 0
  Bot::Training::StarCraft: 0
  Bot::Twatterhose: 0
  Business::IS::PIN: 0
  Crypt::CVS: 0
  DBD::Pg: 0
  DBD::mysql: 0
  Digest::Whirlpool: 0
  Dist::Zilla::PluginBundle::AVAR: 0
  Hailo: 0
  MediaWiki::USERINFO: 0
  Moose: 0
  MooseX::Getopt: 0
  Mouse: 0
  MouseX::Getopt: 0
  Software::License::DWTFYWWI: 0
  Taint::Util: 0
  Task::Bot::Training: 0
  Test::Expect: 0
  Test::Synopsis: 0
  WWW::Mechanize: 0
  YAML::Syck: 0
  perl: v5.10.0
  perl5i: 0
resources:
  Ratings: http://cpanratings.perl.org/d/Task-BeLike-AVAR
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-AVAR
  homepage: http://search.cpan.org/dist/Task-BeLike-AVAR/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/task-belike-avar
version: 0.01
